#! /bin/sh
# Develop the site

# Stop on errors
set -e

cd "$(dirname "$0")/.."

mkdir -p ./site/public
curl -sSLf https://analytics.home-assistant.io/data.json | jq . > ./site/public/data.json

if [ ! -d node_modules ]; then
  script/bootstrap
fi

cd ./site
../node_modules/.bin/vite --open