#! /bin/sh
# Build the worker

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d node_modules ]; then
  script/bootstrap
fi

cd ./worker
../node_modules/.bin/wrangler deploy --dry-run --env=production