#! /bin/sh
# Develop the worker

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d node_modules ]; then
  script/bootstrap
fi

cd ./worker
RUST_BACKTRACE=full ../node_modules/.bin/wrangler dev